### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [berke/aurochs#6]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [do_free](https://github.com/berke/aurochs/blob/637bdc0d4682772837f9e44112212e7f20ab96ff/c/alloc.c#L32-L34)
- [load_file](https://github.com/berke/aurochs/blob/637bdc0d4682772837f9e44112212e7f20ab96ff/c/test/test_nog.c#L36)

**Comment by berke** [comment]
Indeed, free(3) states "If ptr is NULL, no operation is performed".  Thanks, pushed in dd6d1cd.

EDIT: Fix commit number.

**Comment by elfring** [comment]
:thought_balloon: I guess that you would like to refer to an other commit for this issue.

Thanks for [your small source code improvement](https://github.com/berke/aurochs/commit/dd6d1cd331de64a6e5fa6cd3ac4b52134a5091cd "Remove unnecessary null pointer checks").

**Comment by berke** [comment]
You're right, fixed in the comment.
